// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: payment.proto

package payment

import (
	"context"

	"webshop/apps/pay/rpc/pay"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePaymentReq                     = pay.CreatePaymentReq
	CreatePaymentResp                    = pay.CreatePaymentResp
	GetPaymentBySnReq                    = pay.GetPaymentBySnReq
	GetPaymentBySnResp                   = pay.GetPaymentBySnResp
	GetPaymentSuccessRefundByOrderSnReq  = pay.GetPaymentSuccessRefundByOrderSnReq
	GetPaymentSuccessRefundByOrderSnResp = pay.GetPaymentSuccessRefundByOrderSnResp
	PaymentDetail                        = pay.PaymentDetail
	UpdateTradeStateReq                  = pay.UpdateTradeStateReq
	UpdateTradeStateResp                 = pay.UpdateTradeStateResp

	Payment interface {
		// 创建微信支付预处理订单
		CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error)
		// 根据sn查询流水记录
		GetPaymentBySn(ctx context.Context, in *GetPaymentBySnReq, opts ...grpc.CallOption) (*GetPaymentBySnResp, error)
		// 更新交易状态
		UpdateTradeState(ctx context.Context, in *UpdateTradeStateReq, opts ...grpc.CallOption) (*UpdateTradeStateResp, error)
		// 根据订单sn查询流水记录
		GetPaymentSuccessRefundByOrderSn(ctx context.Context, in *GetPaymentSuccessRefundByOrderSnReq, opts ...grpc.CallOption) (*GetPaymentSuccessRefundByOrderSnResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

// 创建微信支付预处理订单
func (m *defaultPayment) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error) {
	client := pay.NewPaymentClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

// 根据sn查询流水记录
func (m *defaultPayment) GetPaymentBySn(ctx context.Context, in *GetPaymentBySnReq, opts ...grpc.CallOption) (*GetPaymentBySnResp, error) {
	client := pay.NewPaymentClient(m.cli.Conn())
	return client.GetPaymentBySn(ctx, in, opts...)
}

// 更新交易状态
func (m *defaultPayment) UpdateTradeState(ctx context.Context, in *UpdateTradeStateReq, opts ...grpc.CallOption) (*UpdateTradeStateResp, error) {
	client := pay.NewPaymentClient(m.cli.Conn())
	return client.UpdateTradeState(ctx, in, opts...)
}

// 根据订单sn查询流水记录
func (m *defaultPayment) GetPaymentSuccessRefundByOrderSn(ctx context.Context, in *GetPaymentSuccessRefundByOrderSnReq, opts ...grpc.CallOption) (*GetPaymentSuccessRefundByOrderSnResp, error) {
	client := pay.NewPaymentClient(m.cli.Conn())
	return client.GetPaymentSuccessRefundByOrderSn(ctx, in, opts...)
}
