// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: payment.proto

package server

import (
	"context"

	"webshop/apps/pay/rpc/internal/logic"
	"webshop/apps/pay/rpc/internal/svc"
	"webshop/apps/pay/rpc/pay"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	pay.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

// 创建微信支付预处理订单
func (s *PaymentServer) CreatePayment(ctx context.Context, in *pay.CreatePaymentReq) (*pay.CreatePaymentResp, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}

// 根据sn查询流水记录
func (s *PaymentServer) GetPaymentBySn(ctx context.Context, in *pay.GetPaymentBySnReq) (*pay.GetPaymentBySnResp, error) {
	l := logic.NewGetPaymentBySnLogic(ctx, s.svcCtx)
	return l.GetPaymentBySn(in)
}

// 更新交易状态
func (s *PaymentServer) UpdateTradeState(ctx context.Context, in *pay.UpdateTradeStateReq) (*pay.UpdateTradeStateResp, error) {
	l := logic.NewUpdateTradeStateLogic(ctx, s.svcCtx)
	return l.UpdateTradeState(in)
}

// 根据订单sn查询流水记录
func (s *PaymentServer) GetPaymentSuccessRefundByOrderSn(ctx context.Context, in *pay.GetPaymentSuccessRefundByOrderSnReq) (*pay.GetPaymentSuccessRefundByOrderSnResp, error) {
	l := logic.NewGetPaymentSuccessRefundByOrderSnLogic(ctx, s.svcCtx)
	return l.GetPaymentSuccessRefundByOrderSn(in)
}
